services:
  webserver-insecure:
    image: nginx
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./conf-insecure/:/etc/nginx/conf.d/:ro
      - ${DATA_DIR}/certbot/www/:/var/www/certbot/:ro
  webserver-secure:
    image: nginx
    ports:
      - 443:443
    restart: unless-stopped
    volumes:
      - ./conf-secure/:/etc/nginx/conf.d/:ro
      - ${DATA_DIR}/certbot/conf/:/etc/letsencrypt/:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot: &certbot
    image: certbot/certbot
    volumes:
      - ${DATA_DIR}/certbot/www/:/var/www/certbot/:rw
      - ${DATA_DIR}/certbot/conf/:/etc/letsencrypt/:rw
    profiles:
      - donotstart
  certbot-autorenew:
    <<: *certbot
    profiles: []
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  main-website:
    image: xinxinw/xin-xin.me
    restart: unless-stopped
  text-edit:
    image: xinxinw/text-edit
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/text-edit-data/:/var/www/html/data/:rw
