services:
  webserver-insecure:
    image: nginx
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./conf-insecure/:/etc/nginx/conf.d/:ro
      - /mnt/thevenin_data/certbot/www/:/var/www/certbot/:ro
  webserver-secure:
    image: nginx
    ports:
      - 443:443
    restart: unless-stopped
    volumes:
      - ./conf-secure/:/etc/nginx/conf.d/:ro
      - /mnt/thevenin_data/certbot/conf/:/etc/letsencrypt/:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - /mnt/thevenin_data/certbot/www/:/var/www/certbot/:rw
      - /mnt/thevenin_data/certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  main-website:
    image: xinxinw/xin-xin.me
    environment:
      - PORT=80
