services:
  webserver-insecure:
    image: nginx
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./conf-insecure/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
  webserver-secure:
    image: nginx
    ports:
      - 443:443
    restart: unless-stopped
    volumes:
      - ./conf-secure/:/etc/nginx/conf.d/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  main-website:
    image: xinxinw/xin-xin.me
    environment:
      - PORT=80
